version: '3.8'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app1
    volumes:
      - ./src/treinamento-laravel:/var/www
    ports:
      - "9000:9000"
    networks:
      - net

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app2
    volumes:
      - ./src/treinamento-laravel:/var/www
    ports:
      - "9001:9000"
    networks:
      - net

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - net

networks:
  net:
    driver: bridge
